### ISSUE TITLE
Unable to deploy to IBM Cloud

### ISSUE THREAD

**Issue by ayatokura** [IBM-Cloud/get-started-java#24]
When I tried steps in the tutorial, the site deployed to the cloud was not displayed correctly.

404 Not Found
The application or context root for this request has not been found: /
<img width="657" alt="Error_JavaApp_IBMCloud" src="https://user-images.githubusercontent.com/12283147/66508889-f12e7780-eb0c-11e9-93e2-cb8096ca6b45.png">

This app works on locally.

**Comment by wbigger** [comment]
I had the same problem with the lite plan, analyzing the logs I found that the problem was the dimension of the JVM. As stated [here](https://cloud.ibm.com/docs/cloud-foundry?topic=cloud-foundry-memory_limits), the default JVM  memory size is 512MB, that doesn't fit on the memory limit of lite plan of 256MB.

I fixed the issue with the following command, as suggested in the page I linked:
```
ibmcloud cf set-env myapp JVM_ARGS -Xmx128m
```
where `myapp` has to be changed with the name of your app, of course.

Hope this help.

**Comment by balajikadambi** [comment]
I am facing the same issue. I have set the memory to 512MB.
<img width="195" alt="image" src="https://user-images.githubusercontent.com/25296042/115716431-ce824d80-a396-11eb-9812-2b00abe6a970.png">

The home page is not found:
![Uploading image.png…]()

**Comment by balajikadambi** [comment]
I was able to workaround by using the OpenLiberty sample instead to run locally.
https://openliberty.io/downloads/

To deploy to IBM Cloud, I followed the below steps:
- run mvn install
- create a manifest.yml as shown below:
```
---
applications:
 - name: openlibdemo
   random-route: true
   path: target/io.openliberty.sample.getting.started.war
   memory: 512M
   instances: 1
```
- run command ibmcloud cf push

**Comment by kevin-ortega** [comment]
You need to append `/GetStartedJava` to the URL.   The tutorial mentions this.

**Comment by balajikadambi** [comment]
@kevin-ortega Yes, appending /GetStartedJava to the URL worked. Thank you.
